services:
  backend:
    build: ./server
    container_name: code-atlas-backend
    ports:
      - "5000:5000"
    env_file:
      - ./server/.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  frontend:
    build: ./client
    container_name: code-atlas-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend